### PR TITLE
Python ESCtoolbox working like Plett's Matlab ESCtoolbox

### PR DESCRIPTION
**Pull request by rafaelsanin**
Hi Gavin,

I'm an aspirant of MsC. in Engineering from the Design Engineering Research Group of EAFIT University, thanks for creating this Python version of Plett's ESCtoolbox, I love Python and hope the modifications I have made can help and motivate others to use Python as a tool for Li-ion battery modeling. 

Kind regards,

### CODE REVIEW

**Comment by wigging** [comment]
Thank you for submitting a pull request. I'll spend some time reviewing the code and will let you know if I have any questions before merging into the main branch.

**Comment by wigging** [comment]
Your pull request has several `__pycache__` folders which contain temporary files that are created by Python when code is executed. These folders and their contents should not be committed in to git. Please remove the folders.

**Comment by rafaelsanin** [comment]
Hi @wigging, pull request updated with __pychache__ deleted, I had some issues with my .gigitnore file from my last commits. Kind regards.

**Comment by wigging** [comment]
Also, please remove the `pickle` module in your code. And don't commit pickled objects to git. In modern Python projects it's better to save results using a plain text format such as CSV or JSON.

**Comment by wigging** [comment]
Here are some articles that discuss the pros and cons of using the `pickle` module:
- https://www.benfrederickson.com/dont-pickle-your-data/
- https://stackoverflow.com/questions/21752259/python-why-pickle
- https://realpython.com/python-pickle-module/#security-concerns-with-the-python-pickle-module

**Comment by rafaelsanin** [comment]
Agree, soon I am going to change pickle to JSON, best for sharing the model results or to use the model in other situations. Kind regards.

**Comment by rafaelsanin** [comment]
Hi Gavin, now the toolbox load and save data in JSON, you can check them at any time, I hope the modifications I have made can be useful, have a great day!

**Comment by wigging** [comment]
Thank you for the modifications. I'll try to review everything this weekend.

**Comment by wigging** [comment]
I ran your pull request and everything seems to work. Thank you for contributing to the repository.

**Pull request merged**
